# Parameters file
# Name of the experiment
exp_id: HeteroGraphSAGE_OPTUNA_TEAV_Cutoff-90_PredHor-60

# Dataset to use
Dataset:
  dataset_name: AIIDKIT
  subdataset: TEAV_Static_Graph_v1
  hdf5_dataset_filename:
    Train: /home/vindasya/Baobab/Codes/aiidkit/data/graph_h5/Cutoff-90/PredHorizon-60/AIIDKIT_TEAV_Graph_TRAIN_CutOffTrain-[90]_CutOffVal-[90]_PredHorizon-60_0.hdf5
    Validation: /home/vindasya/Baobab/Codes/aiidkit/data/graph_h5/Cutoff-90/PredHorizon-60/AIIDKIT_TEAV_Graph_VALIDATION_CutOffTrain-[90]_CutOffVal-[90]_PredHorizon-60_0.hdf5
    Test: /home/vindasya/Baobab/Codes/aiidkit/data/graph_h5/Cutoff-90/PredHorizon-60/AIIDKIT_TEAV_Graph_TEST_CutOffTrain-[90]_CutOffVal-[90]_PredHorizon-60_0.hdf5
  normalize_ds: true
  label_type: infection_label_binary_bacterial

# Device to use
device: cuda:0

# Save information
epochs_step_save_preds: 10


# Architecture to use
Model:
  model_type: GNN
  model_to_use: HeteroGraphSAGE
  hidden_channels: null
  num_layers: null
  dropout: null
  graph_pool_strategy: mean
  graph_pool_fusion: concatenation

# Training parameters
TrainingParams:
  lr: null
  weight_decay: 1.0e-5 # Cannot use 1e-2 as it will be interpreted as a str by PyYAML parser
  batch_size_train: 32
  batch_size_val: 32
  batch_size_test: 32
  n_epochs: 50
  nb_repetitions: 1

# Optimization
Optimization:
  Optuna:
    use_optuna: true
    n_trials: 30
    optuna_starting_point_fn: null
  optimizer: Adam
  loss_function: CE
  EarlyStopping:
    use_early_stopping: true
    patience: 15
    min_delta: 1.0e-4 # Cannot use 1e-2 as it will be interpreted as a str by PyYAML parser

  

