Dataset:
  dataset_name: AIIDKIT
  hdf5_dataset_filename:
    Test: /home/vindasya/Baobab/Codes/aiidkit/data/graph_h5/Cutoff-60/PredHorizon-30/AIIDKIT_TEAV_Graph_TEST_CutOffTrain-[60]_CutOffVal-[60]_PredHorizon-30_0.hdf5
    Train: /home/vindasya/Baobab/Codes/aiidkit/data/graph_h5/Cutoff-60/PredHorizon-30/AIIDKIT_TEAV_Graph_TRAIN_CutOffTrain-[60]_CutOffVal-[60]_PredHorizon-30_0.hdf5
    Validation: /home/vindasya/Baobab/Codes/aiidkit/data/graph_h5/Cutoff-60/PredHorizon-30/AIIDKIT_TEAV_Graph_VALIDATION_CutOffTrain-[60]_CutOffVal-[60]_PredHorizon-30_0.hdf5
  label_type: infection_label_binary_bacterial
  normalize_ds: true
  subdataset: TEAV_Static_Graph_v1
Model:
  dropout: 0.323572275983825
  graph_pool_fusion: stack
  graph_pool_strategy: mean
  hidden_channels: 8
  model_to_use: HeteroGraphSAGE
  model_type: GNN
  num_layers: 2
  out_channels: 1
Optimization:
  EarlyStopping:
    min_delta: 0.0001
    patience: 5
    use_early_stopping: false
  Optuna:
    n_trials: 30
    optuna_starting_point_fn: null
    use_optuna: false
  loss_function: CE
  optimizer: Adam
TrainingParams:
  batch_size_test: 32
  batch_size_train: 32
  batch_size_val: 32
  lr: 0.0016733103443790827
  n_epochs: 50
  nb_repetitions: 1
  weight_decay: 1.0e-05
device: cuda:0
epochs_step_save_preds: 10
exp_id: HeteroGraphSage_Cutoff-60_PredHor-30
